# This is a basic workflow to help you get started with Actions

name: reporting_run

# Controls when the workflow will run
on:
 # schedule:
  #  - cron: "*/2 */1 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
 id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.clientId }}
          tenant-id: ${{ secrets.tenantId }}
          subscription-id: ${{ secrets.subscriptionId }}

      - name: azure clie script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az storage -h

      - name: install dependencies
        run: python -m pip install --upgrade azure-storage-blob azure-identity roboflow requests pandas

      - name: execute reporting run
        run: python -m main.py
