# This is a basic workflow to help you get started with Actions

name: reporting_run

# Controls when the workflow will run
on:
 # schedule:
  #  - cron: "*/2 */1 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      api_key: ${{ secrets.RF_API_KEY }}
      wkspace: ${{ secrets.RF_WORKSPACE }}
    
    steps:
    - name: Checkout repo to runner
      uses: actions/checkout@v4

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas azure-identity azure-storage-blob roboflow

    - name: run main.py
      run: python -m main

    - name: Get Azure connection
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          ls
          az account show
          az storage blob upload-batch --destination rfstats --source . --account-key ${{ secrets.ACCOUNT_KEY }} --account-name ${{ secrets.ACCOUNT_NAME }} --auth-mode key --connection-string ${{ secrets.CONN_STRING }} --pattern "*.csv"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
